Project_Libreria/Project_Libreria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("critica/", include("critica.urls")),
    path("libros/", include("libros.urls")),
    path("listado/", include("listado.urls")),
    path('autenticacion/', include('autenticacion.urls')),
]

Project_Libreria/core/urls.py
from django.urls import path
from . import views

app_name = "core" 

urlpatterns = [
    path("", views.home, name="Home"),
]

Project_Libreria/critica/urls.py
from django.urls import path
from . import views

app_name = "critica"

urlpatterns = [
    path('', views.critica_view, name='critica'),
    path('editar/<int:pk>/', views.editar_critica, name='editar_critica'),
    path('borrar/<int:pk>/', views.borrar_critica, name='borrar_critica'),
]

Project_Libreria/libros/urls.py
from django.urls import path
from . import views

app_name = 'libro'

urlpatterns = [
    path("", views.libro_view, name="libros"),
    path('editar/<int:pk>/', views.editar_libro, name='editar_libro'),
    path('borrar/<int:pk>/', views.borrar_libro, name='borrar_libro'),
]

Project_Libreria/listado/urls.py
from django.urls import path
from . import views

app_name = "listado"
          
urlpatterns = [
    path("", views.home, name="Home"),
]

Project_Libreria/core/views.py
from django.shortcuts import render

# Create your views here.

Project_Libreria/core/templates/core/base.html
<html>

<head>

    {% load static %}

    <!-- Bootstrap -->
    <link href="{% static 'core/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

     <!-- Fonts -->
    
     <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300&display=swap" rel="stylesheet"> 
     <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">
     

    <!-- Styles -->
    <link href="{% static 'core/css/gestion.css' %}" rel="stylesheet">
</head>

<body>

    <h1 class="site-heading text-center text-white d-none d-lg-block">
      
        <span class="site-heading-lower">Biblioteca</span>
      </h1>
      <div style="text-align: right; margin-right: 100px; color: white;">
       
        
      </div>

      <div style="text-align: right; margin-right: 100px; color: white;">
        {% if user.is_authenticated %}
          Hola {{user.username}} &nbsp; &nbsp; <a href="{% url 'cerrar_sesion' %}" style="color: white;">Cerrar sesión</a>
        {% else %}
          <a href="{% url 'logear' %}" style="color: white;">Login</a> &nbsp; &nbsp; <a href="{% url 'autenticacion'%}" style="color: white;">Registrate</a>
        {% endif %}
      </div>


 <!-- Navbar -->
 <nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav">
    <div class="container">
      <a class="navbar-brand text-uppercase text-expanded font-weight-bold d-lg-none" href="{% url 'core:Home' %}">Libros</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav mx-auto">
          <li class="nav-item {% if request.path == '/' %}active{% endif %} px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'core:Home' %}">Inicio</a>
          </li>
          <li class="nav-item {% if request.path == '/listado/' %}active{% endif %} px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'listado:Home' %}">Listado libros</a>
          </li>
          <li class="nav-item {% if request.path == '/libros/' %}active{% endif %} px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'libro:libros' %}">Libros</a>
          </li>
          <li class="nav-item {% if request.path == '/critica/' %}active{% endif %} px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'critica:critica' %}">Critica</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>


<!-- Contenido cambiante -->
{% block content %}

{% endblock %}

    <!-- Footer -->
    <footer class="footer text-faded text-center py-5">
      <div class="container">
        <p class="m-0">
	        <a href="#" class="link">
	          <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
	          </span>
	        </a>
	        <a href="#" class="link">
	          <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
	          </span>
	        </a>
	        <a href="#" class="link">
	          <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-instagram fa-stack-1x fa-inverse"></i>
	          </span>
	        </a>
	    </p>
        <p class="m-0 mbt">
        	<a href="sample.html" class="link">Política de privacidad</a> ·
        	<a href="sample.html" class="link">Aviso legal</a> ·
        	<a href="sample.html" class="link">Cookies</a>
		</p>
        <p class="m-0 mbt1">&copy; Gestión de Pedidos 2020</p>
      </div>
	</footer>

    <!-- Bootstrap -->
    <script src="{% static 'core/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'core/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>


</html>

Project_Libreria/core/templates/core/home.html
{% extends "core/base.html" %}

{% load static %}


{% block content %}
   <!-- Cabecera -->
   <section class="page-section clearfix">
    <div class="container">
      <div class="intro">
        <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{% static 'core/img/principal.jpg' %}" alt="">
        <div class="intro-text left-0 text-center bg-faded p-5 rounded">
          <h2 class="section-heading mb-4" >
            <span class="section-heading-upper">Libreria</span>
            <span class="section-heading-lower">libros</span>
          </h2>
          <p class="mb-3">Ver opiniones
          </p>
         
        </div>
      </div>
    </div>
  </section>


  
    <!-- Message -->
    <section class="page-section cta">
      <div class="container">
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <div class="cta-inner text-center rounded">
              <h2 class="section-heading mb-4">
                <span class="section-heading-upper">"La imaginación comienza con una página"</span>
                <span class="section-heading-lower">Listado de libros</span>
              </h2>
              <p class="mb-0">Más aquí.</p>
            </div>
          </div>
        </div>
      </div>
    </section>
{% endblock %}